---
- name: Debian | Define openjdk java_package
  set_fact:
    java_package: "{{ java.openjdk.debian_package }}"
  when: (java_package|trim == '') and (java_jdk_type == 'openjdk')

- name: Debian | Install WebUpd8 APT key
  apt_key:
    id: "{{ deb.ubuntu.webupd8_key }}"
    keyserver: "{{ deb.ubuntu.webupd8_keyserver }}"
    state: present
  register: get_webupd8_key
  until: get_webupd8_key|success
  retries: 5
  delay: 10
  when: java_jdk_type == 'oracle'

- name: Debian | Add WebUpd8 APT repo
  apt_repository:
    repo: "{{ deb.ubuntu.webupd8_repo }}"
    state: present
  when: java_jdk_type == 'oracle'

- name: Debian | Update APT cache
  apt: update_cache=yes cache_valid_time=86400

- name: Debian | Ensure Java is installed
  apt:
    name: "{{ java_package }}"
    state: present
  register: install_java_command
  when: java_package|trim != ''

- name: Debian | Update system openjdk Java version
  alternatives:
    name: java
    path: "/usr/lib/jvm/java-{{ java_version }}-openjdk-amd64/jre/bin/java"
  when: (not install_java_command is skipped) and java_set_as_default and (java_jdk_type == 'openjdk')